### ISSUE TITLE
GraphQL misconfiguration in Prisma tutorial

### ISSUE THREAD

**Issue by Nargonath** [howtographql/howtographql#738]
Thanks for the great tutorials, they are awesome!

I think there is a little quirk in the chapter `Connecting server and database with Prisma bindings`. When creating the `.graphqlconfig.yml` file at the root of the project, the path to the `prisma.yml` file is off. See below:
```yml

projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml

```
IMO the `prisma` property should be `prisma: src/database/prisma.yml` instead, at least I had to fix it for it to work when calling `prisma deploy`.

I'll make a PR to fix it, thanks again. 😉
